name: Build Wheel Helper

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      artifact_pattern:
        required: true
        type: string
      artifact_path:
        required: true
        type: string
      build_sdist:
        required: false
        type: boolean
        default: false
      setup_armpl:
        required: false
        type: boolean
        default: false
      armpl_version:
        required: false
        type: string
        default: ""

jobs:
  build-wheel:
    name: Build wheel on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Download binaries
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: ${{ inputs.artifact_path }}
          merge-multiple: true

      - name: Cache ArmPL
        id: cache-armpl
        if: inputs.setup_armpl
        uses: actions/cache@v5
        with:
          path: "/opt/arm/armpl_${{ inputs.armpl_version }}_gcc"
          key: armpl-${{ runner.os }}-${{ runner.arch }}-${{ inputs.armpl_version }}

      - name: Check ArmPL
        if: inputs.setup_armpl && steps.cache-armpl.outputs.cache-hit != 'true'
        run: echo "Cache was not hit" && exit 1

      - name: Configure ArmPL
        if: inputs.setup_armpl
        run: |
          "/opt/arm/armpl_${{ inputs.armpl_version }}_gcc/bin/armpl-info"
          echo "LD_LIBRARY_PATH=/opt/arm/armpl_${{ inputs.armpl_version }}_gcc/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" >> "$GITHUB_ENV"

      - name: Build wheel
        run: uv build --wheel

      - name: Repair wheel (Linux)
        if: runner.os == 'Linux'
        run: |
          uvx --with patchelf auditwheel repair --strip dist/*.whl -w repaired_wheels
          rm dist/*.whl
          mv repaired_wheels/*.whl dist/

      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          name: wheel-${{ inputs.os }}
          path: dist/*.whl

  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    if: inputs.build_sdist
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Build sdist
        run: uv build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/*.tar.gz
