name: Build (Windows)

on:
  push:
    paths:
      - 'source/*'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: ''
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache oneMKL
      id: cache-onemkl
      uses: actions/cache@v5
      with:
        path: C:\Program Files (x86)\Intel\oneAPI\mkl
        key: ${{ runner.os }}-onemkl-2025.3.1

    - name: Setup oneMKL
      if: steps.cache-onemkl.outputs.cache-hit != 'true'
      run: |
        curl -s -o onemkl.exe -L https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ae472ff5-aa01-4a72-a452-ce7b559ef041/intel-onemkl-2025.3.1.10_offline.exe
        onemkl.exe -s -a --silent --eula accept

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Download Vector Class Library
      run: |
        curl -s -o vcl.zip -L https://github.com/vectorclass/version2/archive/refs/tags/v2.02.03.zip
        unzip -q vcl.zip
        mv version2*/ vectorclass

    - name: Setup Ninja
      run: pip install ninja

    - name: Setup LLVM
      shell: bash
      run: |
        curl -s -o llvm-win64.exe -LJO https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-win64.exe
        7z x -ollvm llvm-win64.exe

    - name: Configure
      shell: bash
      run: cmake -S . -B build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_COMPILER="$(pwd)/llvm/bin/clang++.exe"
        -D CMAKE_CXX_FLAGS="-Wall -mavx2 -mfma -ffast-math"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        -D MKL_DIR="/c/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/cmake/mkl"
        -D MKL_LINK=static -D MKL_THREADING=sequential -D MKL_INTERFACE=lp64
        -D VCL_HOME="$(pwd)/vectorclass"
        -D VS_INCLUDE_DIR="$(pwd)/vapoursynth/include"

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: cmake --install build --prefix install

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: wnnm-windows-x64
        path: install/bin/*.dll

    - name: Compress artifact for release
      if: inputs.tag != ''
      run: |
        cd install/bin

        mkdir VapourSynth-WNNM-${{ inputs.tag }}
        7z a -t7z -mx=9 ../VapourSynth-WNNM-${{ inputs.tag }}.7z wnnm.dll

    - name: Upload release assets
      if: inputs.tag != ''
      uses: actions/upload-artifact@v7
      with:
        name: release-assets
        path: |
          install/VapourSynth-WNNM-${{ inputs.tag }}.7z

  build-wheel:
    name: Package Wheel (Windows)
    needs: build-windows
    uses: ./.github/workflows/wheel.yml
    with:
      os: windows-latest
      artifact_pattern: wnnm-windows-x64
      artifact_path: install/bin
      build_sdist: false
